name: dart_orm_adapter_mongodb
version: 0.0.5
description: >
  MongoDB adapter for DartORM
author: Ustimenko Sergey <ustims@gmail.com>
homepage: http://github.com/ustims/DartORM-MongoDB
dependencies:
  dart_orm: any
  mongo_dart: ">=0.1.45 <0.2.0"