name: dart_orm_adapter_mongodb
version: 0.1.0-dev
description: >
  MongoDB adapter for DartORM
author: Ustimenko Sergey <ustims@gmail.com>
homepage: http://github.com/ustims/DartORM-MongoDB
dependencies:
  dart_orm: any
  logging: ">=0.9.2 <0.12.0"
  mongo_dart: ">=0.1.45 <0.3.0"
